version: '3'
services:
  validator:
    image: golnarsoar/smartcontracts:latest
    ports:
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 6060:6060
      - 1317:1317
    entrypoint: ['soarchaind', 'start']
    volumes:
      - validator-data:/data/validator
volumes:
  validator-data:
    driver: local
